version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    networks:
      - travel-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.3
    container_name: travel-booking-db
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - travel-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U traveluser -d travel_booking']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  travel-network:
    driver: bridge

volumes:
  db-data:
