version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    networks:
      - travel-network

  db:
    image: postgres:13.3
    container_name: travel-booking-db
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge

volumes:
  db-data:
